title: Dima's Land Project 
description: Ideas and progress on plants, land, cabin in North American zone 5. 
theme: minima
# Collections for sections
collections:
  plants:
    output: true
  land:
    output: true
  shelter:
    output: true
