title: Public Project Tracker
description: Ideas and progress on plants, land, cabin
theme: minima
# Collections for sections
collections:
  plants:
    output: true
  land:
    output: true
  cabin:
    output: true
