title: Land Project
remote_theme: chesterhow/tale
url: "https://dima-things.github.io"
baseurl: "/land-project"

permalink: /:year-:month-:day/:title/
paginate: 5

header_pages:
  - about.md
  - plants/index.md
  - shelter/index.md
  - land/index.md

collections:
  plants:
    output: true
    permalink: /plants/:name/
  land:
    output: true
    permalink: /land/:name/
  shelter:
    output: true
    permalink: /shelter/:name/
