title: Land Project
theme: minima
url: "https://dima-things.github.io"
baseurl: "/land-project"

header_pages:
  - about.md

collections:
  plants:  { output: true }
      permalink: /plants/:name/
  land:    { output: true }
      permalink: /land/:name/
  shelter: { output: true }
    permalink: /shelter/:name/
